nginx:
    image: nginx:alpine
    hostname: nginx
    ports:
        - "80:80"
        - "443:443"
    links:
        - sentry-web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/letsencrypt-www:/tmp/letsencrypt

letsencrypt:
    restart: always
    image: kvaps/letsencrypt-webroot
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./data/letsencrypt:/etc/letsencrypt
        - ./data/letsencrypt-www:/tmp/letsencrypt
    links:
        - nginx
    env_file: env.letsencrypt

redis:
    image: redis:alpine
    hostname: redis
    ports:
        - "6379:6379"
    volumes:
        - "./data/redis:/data"

memcached:
    image: memcached:alpine
    hostname: memcached
    ports:
        - "11211:11211"

postgres:
    image: postgres:alpine
    hostname: postgres
    ports:
        - "5432:5432"
    volumes:
        - "./data/postgres/etc:/etc/postgresql"
        - "./data/postgres/log:/var/log/postgresql"
        - "./data/postgres/lib/data:/var/lib/postgresql/data"

sentry-web:
    image: sentry:8.16
    hostname: sentry
    ports:
        - "9000:9000"
        - "9001:9001"
    env_file: env.sentry
    links:
        - postgres
        - redis
        - memcached
    volumes:
        - ./sentry.conf.py:/etc/sentry/sentry.conf.py:ro

sentry-cron:
    image: sentry:8.16
    hostname: sentry
    command: "sentry run cron"
    env_file: env.sentry 
    links:
        - postgres
        - redis
        - memcached

sentry-worker:
    image: sentry:8.16
    hostname: sentry
    command: "sentry run worker"
    env_file: env.sentry 
    links:
        - postgres
        - redis
        - memcached
